import type { Lead } from '@/types'

const now = '2026-04-01T08:00:00.000Z'

export const DEMO_LEADS_TABLE = 're_outreach_demo_leads'
export const LIVE_LEADS_TABLE = 're_outreach_leads'

export const SEEDED_DEMO_LEADS: Lead[] = [
  {
    id: 'demo-sarah-chen',
    name: 'Sarah Chen',
    email: 'sarah.chen@perthproperty-demo.example',
    phone: '0412 555 101',
    agency_name: 'Perth Property Collective',
    suburb: 'Mount Lawley WA',
    website: 'https://perthproperty-demo.example',
    status: 'new',
    score: 82,
    owner_notes: 'Demo lead for product walkthroughs. Fake contact details only.',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'demo-marcus-doyle',
    name: 'Marcus Doyle',
    email: 'marcus.doyle@riverstone-realty-demo.example',
    phone: '0412 555 102',
    agency_name: 'Riverstone Realty Group',
    suburb: 'South Perth WA',
    website: 'https://riverstone-realty-demo.example',
    status: 'contacted',
    score: 74,
    last_contacted_at: '2026-03-29T03:30:00.000Z',
    owner_notes: 'Use this row to demo contacted-state filtering.',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'demo-priya-nair',
    name: 'Priya Nair',
    email: 'priya.nair@swanriverhomes-demo.example',
    phone: '0412 555 103',
    agency_name: 'Swan River Homes',
    suburb: 'Subiaco WA',
    website: 'https://swanriverhomes-demo.example',
    status: 'replied',
    score: 88,
    last_contacted_at: '2026-03-30T05:00:00.000Z',
    owner_notes: 'Demo lead with reply history.',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'demo-lachlan-price',
    name: 'Lachlan Price',
    email: 'lachlan.price@coastlineagents-demo.example',
    phone: '0412 555 104',
    agency_name: 'Coastline Agents',
    suburb: 'Scarborough WA',
    website: 'https://coastlineagents-demo.example',
    status: 'demo_booked',
    score: 91,
    last_contacted_at: '2026-03-31T01:15:00.000Z',
    next_followup_at: '2026-04-04T02:00:00.000Z',
    owner_notes: 'Useful for demoing post-demo workflow states.',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'demo-ella-morgan',
    name: 'Ella Morgan',
    email: 'ella.morgan@northshoreproperty-demo.example',
    phone: '0412 555 105',
    agency_name: 'Northshore Property Partners',
    suburb: 'Leederville WA',
    website: 'https://northshoreproperty-demo.example',
    status: 'new',
    score: 69,
    owner_notes: 'Great example for AI draft demos.',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'demo-daniel-kwan',
    name: 'Daniel Kwan',
    email: 'daniel.kwan@westedgeagents-demo.example',
    phone: '0412 555 106',
    agency_name: 'West Edge Agents',
    suburb: 'Victoria Park WA',
    website: 'https://westedgeagents-demo.example',
    status: 'won',
    score: 95,
    last_contacted_at: '2026-03-27T06:20:00.000Z',
    owner_notes: 'Demo closed-won example.',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'demo-nina-hart',
    name: 'Nina Hart',
    email: 'nina.hart@foothillrealty-demo.example',
    phone: '0412 555 107',
    agency_name: 'Foothill Realty Studio',
    suburb: 'Kalamunda WA',
    website: 'https://foothillrealty-demo.example',
    status: 'lost',
    score: 57,
    owner_notes: 'Demo closed-lost example.',
    created_at: now,
    updated_at: now,
  },
]

